apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-crud-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-crud-ms
  template:
    metadata:
      labels:
        app: person-crud-ms
    spec:
      containers:
        - name: person-crud-ms
          image: profile-manager-person-crud-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: person-crud-ms
spec:
  type: LoadBalancer
  selector:
    app: person-crud-ms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9000
