apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-crud-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-crud-ms
  template:
    metadata:
      labels:
        app: person-crud-ms
    spec:
      containers:
        - name: person-crud-ms
          image: profile-manager-person-crud-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://admin:password@mongodb:27017/person?authSource=admin&retryWrites=true&w=majority&connectTimeoutMS=10000&socketTimeoutMS=30000&serverSelectionTimeoutMS=30000&retryReads=true"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "800m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: person-crud-ms
spec:
  type: LoadBalancer
  selector:
    app: person-crud-ms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9000