apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-profile-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-profile-ms
  template:
    metadata:
      labels:
        app: person-profile-ms
    spec:
      containers:
        - name: person-profile-ms
          image: profile-manager-person-profile-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: person-profile-ms
spec:
  type: LoadBalancer
  selector:
    app: person-profile-ms
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 9001
